apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-name-test
  description: System for testing scaffolder
  annotations:
    github.com/project-slug: efidemos/sample-react-app
    backstage.io/techdocs-ref: dir:.
  links:
    - url: http://example.comtitle: Example
      
    - url: http://test.com
      
  cmdbId: 46871364
spec:
  owner: group:default/roadie
