apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bmi-calculator
  title: optional title
  description: React app for testing the registration of a new component via template
  annotations:
    github.com/project-slug: efidemos/sample-react-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - react
    - demo
  links:
    - url: http://example.com
      title: Example
      icon: test
      
    - url: http://test.com
      title: Test
      
spec:
  type: service
  lifecycle: production
  owner: group:default/team-alpha
  productOwner: user:default/efi-quynh
  system: system:default/customers-system
