apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bmi-calculator
  title: 
  description: React app for testing the registration of a new component via template
  annotations:
    github.com/project-slug: efidemos/sample-react-app
    backstage.io/techdocs-ref: dir:.
    
  tags:
    - react
    - demo
  links:
    - url: test
      title: test
      icon: test
      
    - url: test2
      title: test2
      spec:
  type: service
  owner: group:default/infrastructure
  
  lifecycle: production
  
  
  dependsOn:
  providesApis:
  consumesApis:
  