apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-name-test
  description: System for testing scaffolder
  annotations:
    github.com/project-slug: efidemos/sample-react-app
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: dfasdf
    sentry.io/project-slug: safd
  tags:
    - test
  labels:
    developer.astrazeneca.com/tag: test
    developer.astrazeneca.com/name: example
  links:
    - url: http://example.com
      title: Example
      
    - url: http://test.com
      title: Test
      
  cmdbId: 31434
spec:
  lifecycle: production
  owner: group:default/team-delta
