apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-name-test
  description: System for testing scaffolder
  annotations:
    github.com/project-slug: efidemos/sample-react-app
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: lkjfdsjlfslkjf
  tags:
    - test
  links:
    - url: http://example.com
      title: Test
    - url: http://test.com
      icon: github
spec:
  owner: group:default/team-charlie
