apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-name-test
  description: System for testing scaffolder
  annotations:
    github.com/project-slug: efidemos/sample-react-app
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: jobby-mcjobberson
    sentry.io/project-slug: sentry-project
    sonarqube.org/project-key: keykeykey
  labels:
    - label1
    - label2
  links:
    - url: http://example.com
      title: Example
      icon: github
      
  cmdbId: 1251245

spec:
  lifecycle: production
  owner: group:default/team-delta
