apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bmi-calculator
  title: bmi-calculator
  description: React app for testing the registration of a new component via template
  annotations:
    github.com/project-slug: efidemos/sample-react-app
    backstage.io/techdocs-ref: docs:. 
    
    
spec:
  type: service
  owner: group:default/team-bravo
  lifecycle: experimental