apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-name-test
  description: System for testing scaffolder
  annotations:
    github.com/project-slug: efidemos/sample-react-app
    backstage.io/techdocs-ref: dir:.
  labels:
    developer.astrazeneca.com/tag: test
    developer.astrazeneca.com/name: example
  links:
    - url: http://example.comtitle: Example
    - url: http://test.comtitle: Test

  cmdbId: 1231
spec:
  lifecycle: production
  owner: group:default/team-delta
